### ISSUE TITLE
AiiDA as profile in Jupyterhub

### ISSUE THREAD

**Issue by obgeneralao** [aiidalab/aiidalab-k8s#7]
I tried to add AiiDA lab as a profile in jupyterhub in my GKE cluster. It got stucked in Spawning and throw an error.Did I miss something below?

```yaml
singleuser:
  extraEnv:
    EDITOR: "nano"
  image:
    name: jupyter/tensorflow-notebook
    tag: latest #ee44fe9e57db7d58312ce96c46f134cd3bd72e6c
  profileList:
    - display_name: "Tensorflow environment"
      description: "For Machine Learning"
      default: true
    - display_name: "AiiDA environment"
      description: "If you want to visualize the Provenance of your data and calculations."
      kubespawner_override:
        image: aiidalab/aiidalab-docker-stack:latest                      
        image_pull_policy: Always
        cmd: /sbin/my_my_init
        fs_gid: 1000
        environment:
            - NB_USER: "aiida"
            - NB_UID: "1000"
            - NB_GID: "1000"
        http_timeout: 300   
        uid: 0
        gid: 1000
        # volumes:
            # -name: hub-templates
        # volume_mounts:
            # -mountPath: /etc/jupyterhub/templates
            # -name: hub-templates
```

**Comment by csadorf** [comment]
@obgeneralao I do not see any obvious error with the configuration. Do you remember what error was thrown? Was there an error message? If you have a screenshot that would be ideal. Are you able to access the logs of the hub node?

A guess: It's possible that the timeout of 5mins was still too short. We are working on greatly improving the startup speed at the moment, but maybe the spawner still took to long with the image version you tested?

**Comment by obgeneralao** [comment]
I am new to this but thank you for letting me know to check the log. I noticed some error because of this

```yaml
 environment:
            - NB_USER: "aiida"
            - NB_UID: "1000"
            - NB_GID: "1000"
```

I changed it to

```yaml
environment: {"NB_USER": "aiida", "NB_UID": "1000" , "NB_GID": "1000" }
```

And I was able to login to AiiDAlab successfully.

Thanks a lot. I appreciate it.
